spring:
  application:
    name: hello-spring-cloud-web-admin-feign
  thymeleaf:
    servlet:
      content-type: text/html
    mode: HTML
    cache: false
    encoding: UTF-8
server:
  port: 8765

eureka:
  client:
    service-url:
      defaultUrl : http://localhost:8761/eureka
feign:
  hystrix:
    enabled: true
